CREATE TABLE [dbo].[Groups]
(
	[Id] INT NOT NULL CONSTRAINT PK_Group PRIMARY KEY IDENTITY,
	[Name] VARCHAR(50) NOT NULL,
	[IdAdminUser] INT NOT NULL CONSTRAINT FK_Groups_AdminUser FOREIGN KEY REFERENCES Users(Id)
)
