CREATE TABLE [dbo].[MessageUsers]
(
	[Id] INT NOT NULL CONSTRAINT PK_MessageUser PRIMARY KEY IDENTITY,
	[IdUserFrom] INT NOT NULL CONSTRAINT FK_MessageUsers_UserFrom FOREIGN KEY REFERENCES Users(Id),
	[IdUserTo] INT NOT NULL CONSTRAINT FK_MessageUsers_UserTo FOREIGN KEY REFERENCES Users(Id),
	[Content] TEXT NOT NULL,
	[Status] INT NOT NULL,
	[DateTime] DATETIME NOT NULL
)
